---
# ===== DB SECRET TEMPLATE =====
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: bookstore-ns
type: Opaque
stringData:
  host: "bookstore-db-dev.cluster-chqmsk84awi5.us-east-1.rds.amazonaws.com"
  username: "root"
  password: "fakepass"

---
# ===== CRM SECRET TEMPLATE =====
apiVersion: v1
kind: Secret
metadata:
  name: crm-secret
  namespace: bookstore-ns
type: Opaque
stringData:
  smtp-user: "momodouseringkhan95@gmail.com"
  smtp-pass: "fakepass"
---
# ===== API KEYS SECRET =====
apiVersion: v1
kind: Secret
metadata:
  name: api-keys-secret
  namespace: bookstore-ns
type: Opaque
stringData:
  gemini-key: "fakepass"